language: node_js
arch:
  - amd64
  - ppc64le
# Removing 0.10 and testing with latest versions
node_js:
  - 14
  - node
  - lts/*
before_script:
  - 'npm install -g grunt-cli'
  - 'npm install -g bower'
  - 'bower install'
script: grunt test
after_script: "npm install coveralls@2.10.0 && cat ./coverage/*/lcov.info | coveralls"
